### ISSUE TITLE
Unable to shake Erik's hand

### ISSUE THREAD

**Issue by marauderz** [erik-smit/sony-camera-api#1]
I just got myself a QV10, and was horribly disappointed at the APIs which were exposed by Sony but left so many things off the table. I was monitoring network packets and was about to get the the accessControl URL when I finally stumbled on your code. I was worried if there was a key involved how would I go about to retrieving it. 

But finding your code means I don't need to attempt any hacking into the code now. May I ask how did you find the KeyDG, Developer ID and Developer Name fields? 

Once again, thanks a LOT for this!

**Comment by erik-smit** [comment]
Thank you for your kind words. I'm quite proud of this achievement myself.

The Developer ID and Name fields were found in the apk.
The DG field is provided by the actEnableMethod JSON RPC: [here](https://github.com/erik-smit/sony-camera-api/blob/master/actEnableMethods.sh#L22)

**Comment by marauderz** [comment]
Yeah, I've been searching around the net, and seen some of your other post. You say that KeyDG is generated by the cert, is a some sort of hash of the Sony Corporation's SSL cert? Maybe the thumbprint or CN name?

**Comment by erik-smit** [comment]
I do not know for sure how KeyDG is produced. 

But I think it is some function (hash, etc.) containing the certificate that was used to sign the apk.
If you modify the apktool and resign the .apk, the result can no longer connect to the camera.

**Comment by ledelec** [comment]
Where did you find KeyDG?

**Comment by erik-smit** [comment]
> Where did you find KeyDG?

I looked at the hashing functions called by the APK, hooked them and logged them.
