### ISSUE TITLE
There are no necessary methods in actEnableMethods.h

### ISSUE THREAD

**Issue by cosmicog** [erik-smit/sony-camera-api#2]
Hi, I've tried to change the methods parameter but When I add `camera/startMovieRec` like functions for my QX1 to there;
`/params/0/methods=camera/setFlashMode:camera/getFlashMode:camera/getSupportedFlashMode:camera/getAvailableFlashMode:camera/setExposureCompensation:camera/getExposureCompensation:camera/getSupportedExposureCompensation:camera/getAvailableExposureCompensation:camera/setSteadyMode:camera/getSteadyMode:camera/getSupportedSteadyMode:camera/getAvailableSteadyMode:camera/setViewAngle:camera/getViewAngle:camera/getSupportedViewAngle:camera/getAvailableViewAngle:camera/setMovieQuality:camera/getMovieQuality:camera/getSupportedMovieQuality:camera/getAvailableMovieQuality:camera/setFocusMode:camera/getFocusMode:camera/getSupportedFocusMode:camera/getAvailableFocusMode:camera/setStillSize:camera/getStillSize:camera/getSupportedStillSize:camera/getAvailableStillSize:camera/setBeepMode:camera/getBeepMode:camera/getSupportedBeepMode:camera/getAvailableBeepMode:camera/setCameraFunction:camera/getCameraFunction:camera/getSupportedCameraFunction:camera/getAvailableCameraFunction:camera/setLiveviewSize:camera/getLiveviewSize:camera/getSupportedLiveviewSize:camera/getAvailableLiveviewSize:camera/setTouchAFPosition:camera/getTouchAFPosition:camera/cancelTouchAFPosition:camera/setFNumber:camera/getFNumber:camera/getSupportedFNumber:camera/getAvailableFNumber:camera/setShutterSpeed:camera/getShutterSpeed:camera/getSupportedShutterSpeed:camera/getAvailableShutterSpeed:camera/setIsoSpeedRate:camera/getIsoSpeedRate:camera/getSupportedIsoSpeedRate:camera/getAvailableIsoSpeedRate:camera/setExposureMode:camera/getExposureMode:camera/getSupportedExposureMode:camera/getAvailableExposureMode:camera/setWhiteBalance:camera/getWhiteBalance:camera/getSupportedWhiteBalance:camera/getAvailableWhiteBalance:camera/setProgramShift:camera/getSupportedProgramShift:camera/getStorageInformation:camera/startLiveviewWithSize:camera/startIntervalStillRec:camera/stopIntervalStillRec:camera/actFormatStorage:system/setCurrentTime`

The camera responses with "illegal argument" error. How can I add my needed functions to that list? Is it about some `sha256` hash?

**Comment by erik-smit** [comment]
I don't know why the camera doesn't accept it.
I don't think you can just add arbitrary methods to the list.
I think maybe the methods-list is related to the versioning of something.

Did you see the official application make a request with camera/startMovieRec in the list of functions?
Do you even need to unlock startMovieRec? I thought it was an open function.

**Comment by cosmicog** [comment]
Maybe. On the Android, official PlayMemories Mobile application can do everything even the receiving in-camera images (Wifi API's reference pdf says qx100 does not supported wifi image transfer, but application can) And official app can record movies too.

Anyway, I've already solved the problem :) Now I can photos and videos from C++ plugin. But I need to set date/time now. May I use this `actEnableMethods.h` directly in my repo? :) Thanks!

**Comment by erik-smit** [comment]
> May I use this actEnableMethods.h directly in my repo? :) Thanks!

Sure.
Please credit if possible.

**Comment by cosmicog** [comment]
Of course I will :)
